### ISSUE TITLE
modificar el back para que traiga el listado de cuentas contables por naturaleza y las liste en `conceptos/cuentas-contabbles`

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/contabilidad_cliente#112]
> Quedaría modificar el servicio del back para que traiga el listado de cuentas contables por naturaleza y las liste en el componente de `conceptos/cuentas-contabbles`
> 
> 
> Tarea  en un 95%

_Originally posted by @Soulfilip-UD in https://github.com/udistrital/contabilidad_cliente/issues/25#issuecomment-587236789_

**Comment by Jeisson005** [comment]
Se encuentra que:

El cliente actualmente ya consulta un endpoint que lista las cuentas contables por naturaleza en **conceptos/cuentas-contables**, esto se puede visualizar en el [componente](https://github.com/udistrital/contabilidad_cliente/blob/develop/src/app/pages/conceptos/cuentas-contables/cuentas-contables.component.ts#L135), allí utilizando el método **getCuenta** del **arbolHelper**, se solicita el listado de cuentas contables crédito y débito respectivamente de los siguientes endpoints:
- https://autenticacion.portaloas.udistrital.edu.co/apioas/cuentas_contables_crud/v1/nodo_cuenta_contable/cuentas/credito?fullTree=true
- https://autenticacion.portaloas.udistrital.edu.co/apioas/cuentas_contables_crud/v1/nodo_cuenta_contable/cuentas/credito?fullTree=true

![image](https://user-images.githubusercontent.com/24659130/132802225-f3651f38-8829-49a8-ab10-9257a187c035.png)


Sin embargo, después de lo realizado en el issue #101, se encuentra que esta vista debe ser cambiada casi por completo, por lo que se propuso el [mockup](https://docs.google.com/presentation/d/1v6sG0vrEnpfTgweViAyywOI8MTv-MAX934rlAPrK4gk/edit?usp=sharing) correspondiente, que una vez aprobado debe ser desarrollado, adicionalmente con lo realizado en #113, se cuentan con nuevos endpoints que son los que deben utilizarse en el nuevo desarrollo para el consumo de cuentas contables.

**Conclusión:**
Este issue se puede cerrar simplemente teniendo en cuenta que se cambiará esa vista y que cuando se haga ese desarrollo se deben consumir el nuevo endpoint para el consumo de cuentas contables (#113)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
