### ISSUE TITLE
Retornar solo cuentas de último nivel

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/contabilidad_cliente#113]
Peticion de Arbol Cuentas (Credito y Debito) que retorne solo cuentas de último nivel (se requiere particularmente en Arka, y posiblemente en otras partes más de Kronos - Confirmar con mariac y con Jeisson - y de pronto con Ludwing(Arka) )

Al final de la mesa de trabajo de Arka del 27/07/21 se mencionó que, finalmente para los movimientos solo se pueden usar
- Cuentas de nivel (digitos) 6 o mayor (El-nivel/los-dígitos podrían establecerse en un ~~parámetro~~ ajuste del sistema)
- Cuentas "sin hijos" (no intermedias)

- [x] Confirmar con analista (y Contabilidad, ~~de ser necesario~~)
- [x] Identificar si los endpoint que retornan la lista de cuentas cr/db se les puede pasar un parámetro para filtrar y qué tanto admite
- [x] (De ser necesario) Agregar controlador nuevo, que retorne las cuentas que cumplan ambos criterios

Tomar como punto de partida, las peticiones que se hacen desde Arka
![image](https://user-images.githubusercontent.com/6588872/127537195-bdd6c210-feb8-42b7-bc2b-005010675f8f.png)

Como esto lo necesitamos en varias partes, considerar un controlador dedicado y/o revisar el controlador actual para que se le puedan pasar más parámetros de filtrado, o revisar si de hecho ya los admite

**Comment by Jeisson005** [comment]
Se realiza lo siguiente:

- Se valida con @mcrubianot, encontrando que efectivamente se requiere el filtro descrito
- Análisis endpoint actual **nodo_cuenta_contable/getNodosCuentaArka/_:NaturalezaCuentaContable_**, encontrando que no cuenta con más opciones de paso de parámetros o filtros
- Creación del endpoint **nodo_cuenta_contable/cuentas** con los parámetros **query**, limit y offset para mayor flexibilidad en las consultas mediante el consumo de la API
- Creación del endpoint **nodo_cuenta_contable/getCuentas/_:NaturalezaCuentaContable_** facilitando la solicitud de cuentas sin hijos (de "máximo nivel") ya sea débito o crédito

### Resultado
Aquí un ejemplo del resultado de la solicitud a **.../nodo_cuenta_contable/getCuentas/credito**:
```json
{
    "Body": [
        {
            "Codigo": "611078ad8836b0002afa9b37",
            "DetalleCuentaID": "iva",
            "Naturaleza": "credito",
            "Nombre": "Cuenta de prueba"
        }
    ],
    "Code": 200,
    "Message": null
}
```

**Comment by AlexFBP** [comment]
Tener en cuenta si #87 aplica

**Comment by Jeisson005** [comment]
Para que las cuentas inactivas no se usen, se crea el parámetro **withInactives**, que por defecto es falso, de esta forma en los endpoints **/cuentas** y **/getCuentas/:NaturalezaCuentaContable** se traen por defecto solo las cuentas activas, y para traer las inactivas se debe cambiar el parámetro a verdadero
