### ISSUE TITLE
Interface de asignar conceptos a una cuenta contable

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/contabilidad_cliente#25]
Se requiere una interface desde la que se puedan gestionar los conceptos y se puedan asociar a una cuenta contable.

Los servicios de los conceptos y asociación a cuentas contables ya quedaron en el PR [#33](https://github.com/udistrital/cuentas_contables_crud/pull/33)

**Comment by Soulfilip-UD** [comment]
Los servicios del CRUD de conceptos ya están listos para ser usados.

**Comment by Soulfilip-UD** [comment]
Se realizan los siguientes mockups basados en la necesidad:

1. Wizard crear conceptos y catalogo de conceptos
![mock-comceptos-1](https://user-images.githubusercontent.com/50924615/73486321-e4ab8480-4372-11ea-9d51-65da534805fb.jpg)

2. Cada paso del wizard
![mock-comceptos-1](https://user-images.githubusercontent.com/50924615/73486393-0e64ab80-4373-11ea-8e47-a196caecb9ed.png)

En la edición se reutilizara el componente del wizard y el delete con un modal usado anteriormente.

**Comment by Soulfilip-UD** [comment]
Se modifica el modelo de conceptos:
`{
      "FechaCreacion": "2020-02-05",
      "FechaModificacion": "2020-02-05",
      "Activo": true,
      "ID": "5e3a1b4a3b5784c173035eae",
      "Nombre": "Concepto prueba",
      "CuentaDebito": "1-2-11",
      "CuentaCredito": "1-1-11",
      "MovimientoID": "01-movimiento"
    }`

**Comment by Soulfilip-UD** [comment]
Se sube la primera versión de la vista :
<img width="1349" alt="Screen Shot 2020-02-05 at 7 29 57 PM" src="https://user-images.githubusercontent.com/50924615/73895542-ed59fa00-484d-11ea-9534-fb1a1fdf731c.png">

**Comment by Soulfilip-UD** [comment]
![Screen Shot 2020-02-17 at 8 52 21 PM](https://user-images.githubusercontent.com/50924615/74697098-9518e580-51c7-11ea-8fb0-f5e37842d263.png)
![Screen Shot 2020-02-17 at 8 52 41 PM](https://user-images.githubusercontent.com/50924615/74697100-977b3f80-51c7-11ea-9069-c19309271379.png)
![Screen Shot 2020-02-17 at 8 52 55 PM](https://user-images.githubusercontent.com/50924615/74697102-977b3f80-51c7-11ea-883b-9993ef7f114c.png)
![Screen Shot 2020-02-17 at 8 53 26 PM](https://user-images.githubusercontent.com/50924615/74697103-9813d600-51c7-11ea-8074-7cc259049a4a.png)

Quedo super play!!

**Comment by Soulfilip-UD** [comment]
Quedaría modificar el servicio del back para que traiga el listado de cuentas contables por naturaleza y las liste en el componente de `conceptos/cuentas-contabbles`


Tarea  en un 95%

**Comment by AlexFBP** [comment]
Se abrió un Issue para abordar [el tema pendiente](#issuecomment-587236789). Se cierra este Issue
