### ISSUE TITLE
realizar limpieza de codigo no usado en cliente de contabilidad

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/contabilidad_cliente#39]
se requiere realizar una limpieza de código basura horade del cliente de presupuesto al cliente contabilidad con el fin de evitar tener código basura o código no usado, proporcionando mayor rapidez en compilación de la aplicación y  en su rendimiento

**Comment by Jeisson005** [comment]
Se realiza limpieza de código y archivos no utilizado

- [ ] Data: Archivos de datos y servicios que no están en uso

- [ ] Helpers que no están en uso

- [ ] Interfaces: se elimina esta carpeta y su contenido

- [ ] Mock: Se elimina esta carpeta, sus componentes y servicios

- [ ] Utils: Se eliminan los servicios que no se usan

- [ ] Pages/Layouts: Se queda solo el layout que se usa

- [ ] Pages/Miscellaneus: Se queda solo el componente de "not-found"

- [ ] @theme/layout: Se queda solo el layout que se utiliza

- [ ] assets: Se eliminan archivos de images que no están en uso

**Comment by BOTOOM** [comment]
tiempo de compilación antes de la limpieza

![image](https://user-images.githubusercontent.com/28914781/97272243-9e9b2880-17ff-11eb-8f47-a3ce98327edf.png)

tiempo de compilación después de la limpieza
![image](https://user-images.githubusercontent.com/28914781/97272330-bd012400-17ff-11eb-9194-56355ea7b1b4.png)

el tiempo se ha reducido casi a la mtad
