### ISSUE TITLE
Elimnar branch innecesarios 

### ISSUE THREAD

**Issue by jjvargass** [udistrital/contabilidad_cliente#49]
se deben eliminar los branch que ya fueron integrados o actualizados al nuevo lineaminto de la oas.

**Comment by AlexFBP** [comment]
Se procederá de manera similar a udistrital/arka_cliente#635

**Comment by AlexFBP** [comment]
Solo quedaron [ramas](https://github.com/udistrital/contabilidad_cliente/branches) develop y master:
![image](https://user-images.githubusercontent.com/6588872/124210094-75c6e380-dab0-11eb-95d6-38e21b1bb42d.png)

De acuerdo al [lineamiento](https://github.com/udistrital/lineamientos_oas/blob/5cd20a3012a5c28bb7588b1d24ed89b471ce3f07/repositorios_institucionales/nombre_branch.md), para los release el orden será:
1. Crear la rama del release
2. Fusionarla a master y a develop
3. Realizar el tag. Si la rama release/* se fusionó a master, el tag se hará sobre el commit de fusión. De ser solo un release interno (no fusionado a master), el tag se hará sobre el último commit de la rama release/*.
4. Eliminar la rama release

Se procederá de manera similar con las ramas hotfix, igualmente en acuerdo al lineamiento
