### ISSUE TITLE
Mockups Provisiones

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/contabilidad_cliente#60]
Es necesario crear los mockups para Provisiones

**Comment by NRDaza** [comment]
Se crean Mockups en el siguiente [Enlace](https://drive.google.com/file/d/1wVlqar86VVAei4BcQqBufq7wGcr8fZW_/view?usp=sharing)

**Comment by ManuelMurillo** [comment]
la Socializacion de asocia en el siguiente issue #61
