### ISSUE TITLE
Socializar Mockups de Provisiones

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/contabilidad_cliente#61]
Es necesario socializar los mockups de provisiones

**Comment by NRDaza** [comment]
Se realiza una primera socialización con María C. de los  [Mockups de provisiones](https://drive.google.com/file/d/1wVlqar86VVAei4BcQqBufq7wGcr8fZW_/view?usp=sharing)

Se realizan las siguientes correcciones.

- [ ] Agregar campo de suma total de provisiones

- [ ] Separar en la tabla de resumen el porcentaje de las provisiones

- [ ] Corrección de nombre valor concepto nómina a valor concepto cesantías.

- [ ] Ajustes a la tabla de contabilización

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
