### ISSUE TITLE
Realizar vistas de conciiaciones

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/contabilidad_cliente#66]

**Comment by NRDaza** [comment]
# ENDPOINTS
## CONTABILIDAD
http://localhost:4200/#/pages/conciliaciones/lista

http://localhost:4200/#/pages/conciliaciones/crear

## TESORERÍA
http://localhost:4200/#/pages/conciliaciones/conciliacion

http://localhost:4200/#/pages/conciliaciones/contabilizacion

# VISTAS


- [ ] Lista conciliaciones
![tabla](https://user-images.githubusercontent.com/34488581/111534648-390bf200-8736-11eb-8727-c6949f866969.PNG)

- [ ] generar conciliación
![generar1](https://user-images.githubusercontent.com/34488581/111534638-37dac500-8736-11eb-86bc-64987cd2411a.PNG)
![generar2](https://user-images.githubusercontent.com/34488581/111534639-37dac500-8736-11eb-8061-141a9a10571c.PNG)

- [ ] Documento Extracto
![extracto](https://user-images.githubusercontent.com/34488581/111534635-37422e80-8736-11eb-90dd-ff0fe2a41904.PNG)
- [ ] Documento Mov. Contable
![mov](https://user-images.githubusercontent.com/34488581/111534647-390bf200-8736-11eb-9267-193ca7d05bb4.PNG)
- [ ] Documento Estado de pago
![estado](https://user-images.githubusercontent.com/34488581/111534633-36a99800-8736-11eb-8ec3-df8d631dd660.PNG)
- [ ] Libros Débito
![librosd](https://user-images.githubusercontent.com/34488581/111534645-38735b80-8736-11eb-9fc5-3c21b3c7c066.PNG)
- [ ] Libros Crédito
![librosc](https://user-images.githubusercontent.com/34488581/111534643-38735b80-8736-11eb-95bb-975b5eeeb210.PNG)
- [ ] Extracto Débito
![extractod](https://user-images.githubusercontent.com/34488581/111534637-37422e80-8736-11eb-8670-6d15ec0eeb82.PNG)
- [ ] Extracto Crédito
![extractoc](https://user-images.githubusercontent.com/34488581/111534636-37422e80-8736-11eb-841a-1e0ef40390e6.PNG)
- [ ] Conciliación
![conciliacion](https://user-images.githubusercontent.com/34488581/111534629-36110180-8736-11eb-8760-0b3d3aeae897.PNG)
- [ ] Guardar
![guardar](https://user-images.githubusercontent.com/34488581/111534641-38735b80-8736-11eb-9612-b39a74397fab.PNG)
- [ ] Contabilización libros débito
![contabilziacionD](https://user-images.githubusercontent.com/34488581/111534632-36a99800-8736-11eb-8144-c3332edfe890.PNG)
- [ ] Contabilización libros Crédito
![contabilziacionC](https://user-images.githubusercontent.com/34488581/111534631-36a99800-8736-11eb-89a9-367f4277e00b.PNG)
- [ ] Aprobar
![aprobar](https://user-images.githubusercontent.com/34488581/111534627-36110180-8736-11eb-9b3e-7136e9426f85.PNG)
