### ISSUE TITLE
Vista Comprobantes y tipo de comprobantes

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/contabilidad_cliente#7]
- [x] Revisar [HU](https://docs.google.com/spreadsheets/d/1AjwlomSd4LFDXR5FkoKx0M06awqKabSv/edit#gid=1055638300)

- [x] Agregar links al menu

- [x] Agregar Vistas de Tipo Comprobante y Comprobante

- [x] Agregar Vista para Agregar Parametros

**Comment by davidmm07** [comment]
Luego de subir los anteriores cambios la tarea esta en un 85%

- [ ] Pendiente agregar parametros.
- [ ] Corregir transacción desde el api para comprobante.

**Comment by davidmm07** [comment]
- [ ] Corregir la selección de los datos de tipo select que se visualice en datos ya insertados.

**Comment by davidmm07** [comment]
Tarea a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Buen trabajo

Tarea Finalizada
Proceeding to close Issue 👾
