### ISSUE TITLE
Permitir inactivar cuentas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/contabilidad_cliente#86]
- [x] Identificar relación entre la columna "Activo" y el CRUD respectivo...
- [x] Si se puede cambiar el estado: Mostrar checkbox / switch deslizante / radius en el formulario de edición/ver la cuenta
- [x] Si NO se puede cambiar la inactivación. mostrar un botón "Inactivar"

**Comment by Jeisson005** [comment]
Se decide crear una lista desplegable para cambiar el estado de la cuenta.
En caso de que solo se pueda inactivar una vez se debe deshabilitar el campo una vez se encuentre inactivo.
![image](https://user-images.githubusercontent.com/24659130/125699455-498f0cb1-40b0-47d9-b29a-0fd47dcd1ff6.png)

**Comment by AlexFBP** [comment]
Fusionado
