### ISSUE TITLE
Campo "cuenta alterna" debe ser opcional

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/contabilidad_cliente#91]
- [x] Agregar campo "Requiere cuenta alterna?" SI/NO
- [x] Cuando esté en SI, pedir la cuenta alterna
- [x] Campo de # de cuenta alterna, cargarlo de las demas cuentas existentes
- [x] Mostrar nombre de la cuenta alterna

**Comment by Jeisson005** [comment]
El resultado es el siguiente
![image](https://user-images.githubusercontent.com/24659130/125659751-415cae84-fc63-4183-9ca6-236b85c82bde.png)

**Comment by AlexFBP** [comment]
Se podría mover el código para permitir visualizar nombres de cuentas más largas, cuando aplique
![image](https://user-images.githubusercontent.com/6588872/125701747-37d411de-b5a6-4aab-abde-30b2cd8735c0.png)

**Comment by Jeisson005** [comment]
Se cambia el tamaño de los campos, el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/24659130/125707663-0739e732-d3ce-4243-9e4b-aac9a2d91cfe.png)
